version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven
      - echo "Maven executable $(which mvn)"
      - echo "version $(mvn --version)"
  pre_build:
    commands:
      - echo Logging in...
  build:
    commands:
      - echo Building gatewayservice...
      - cd gatewayservice
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir -p build
      - cp gatewayservice/target/*.jar build/
artifacts:
  files:
    - build/**/*
    - gatewayservice/appspec.yml
    - gatewayservice/scripts/**/*