version: 0.0
os: linux
files:
  - source: /
    destination: /opt/taskservice
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 20
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 20
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 20